[package]
name = "text-generation-benchmark"
version = "0.1.0"
edition = "2021"
authors = ["Olivier Dehaene"]
description = "Text Generation Benchmarking tool"

[lib]
path = "src/lib.rs"

[[bin]]
name = "text-generation-bench"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.4", features = ["derive", "env"] }
itertools = "0.10.5"
plotters = "0.3.4"
text-generation-client = { path = "../router/client" }
thiserror = "1.0.38"
tokenizers = "0.13.2"
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "parking_lot", "signal", "sync"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }

