repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: docs/source/basic_tutorials/launcher.md
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
-   repo: local
    hooks:
    -   id: check-openapi-update
        name: check openapi spec update
        entry: python
        language: system
        pass_filenames: false
        always_run: true
        args:
            - -c
            - |
              import os
              import sys
              import subprocess

              def get_changed_files():
                  result = subprocess.run(['git', 'diff', '--name-only'], capture_output=True, text=True)
                  return result.stdout.splitlines()

              changed_files = get_changed_files()
              router_files = [f for f in changed_files if f.startswith('router/')]

              if not router_files:
                  print("No router files changed. Skipping OpenAPI spec check.")
                  sys.exit(0)

              openapi_file = 'docs/openapi.json'
              if not os.path.exists(openapi_file):
                  print(f"Error: {openapi_file} does not exist.")
                  sys.exit(1)

              if openapi_file not in changed_files:
                  print(f"Error: Router files were updated, but {openapi_file} was not updated.")
                  sys.exit(1)
              else:
                  print(f"{openapi_file} has been updated along with router changes.")
                  sys.exit(0)
