[workspace]
members = [
    "router",
    "router/client",
    "router/grpc-metadata",
    "launcher",
    "benchmark"
]
exclude = [
]

[profile.release]
debug = 1
incremental = true
lto = "off"
panic = "abort"
