apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "text-generation-inference.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "text-generation-inference.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: text-generation-inference
  selector:
    matchLabels:
      {{- include "text-generation-inference.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: text-generation-inference
      labels:
        {{- include "text-generation-inference.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: text-generation-inference
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: 80
          command:
            - "text-generation-launcher"
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: "/data"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.storage }}
