name: Automatic Documentation for Launcher

on:
  pull_request:

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Launcher
      id: install-launcher
      run: cargo install --path launcher/

    - name: Install router
      id: install-router
      run: cargo install --path router/

    - name: Check that documentation is up-to-date
      run: |
        python update_doc.py --check
