name: Automatic Documentation for Launcher

on:
  pull_request:

jobs:
  update_docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Launcher
      id: install-launcher
      run: cargo install --git https://github.com/${{ github.repository }} --branch ${{ github.head_ref }} text-generation-launcher
    
    - name: Update Docs
      run: |
        echo text-generation-launcher --help
        output=$(text-generation-launcher --help)
        { echo '```'; echo $output; echo '```'; } > launcher_test.md
        diff launcher_test.md docs/source/basic_tutorials/launcher.md
